language: php
matrix:
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
sudo: false
before_install: composer self-update
install: composer update --prefer-dist --no-interaction --no-suggest
script: vendor/bin/phpunit
